# .github/workflows/postdeploy-sitemap.yml
name: Generate Sitemap After Deploy

on:
  push:
    branches:
      - main

jobs:
  generate-sitemap:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Generate Sitemap
        run: npm run generate-sitemap

      - name: Commit Updated Sitemap
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add public/sitemap.xml
          git commit -m "chore: update sitemap.xml"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
